function M_num = get_M_matrix(q1,q2,q3)
%get_M_matrix
%    M_num = get_M_matrix(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2026-01-04 20:53:41

t2 = cos(q3);
t3 = q2.*2.0;
t4 = q3.*2.0;
t5 = cos(t3);
t6 = q3+t3;
t8 = t3+t4;
t10 = t2.*3.67394039744206e-18;
t11 = t2.*7.347880794884119e-18;
t16 = t2.*6.0e-2;
t7 = cos(t6);
t9 = cos(t8);
t13 = t10+1.83697019872103e-18;
t15 = t11+1.653273178848927e-17;
t12 = t7.*1.124819836996393e-34;
t14 = t9.*4.218074388736475e-35;
t17 = t12+t14+t16+2.25e-2;
et1 = t2.*6.0e-2;
et2 = t5.*1.1e-1;
et3 = t7.*6.0e-2;
et4 = t9.*1.125e-2;
et5 = 2.4875e-1;
et6 = t2.*1.2e-1;
et7 = t5.*4.124339402320109e-34;
et8 = t7.*2.249639673992787e-34+t14;
et9 = 2.425e-1;
M_num = reshape([et1+et2+et3+et4+et5,t15,t13,t15,et6+et7+et8+et9,t17,t13,t17,t14+2.25e-2],[3,3]);
end
