function G_num = get_G_vector(q1,q2,q3)
%get_G_vector
%    G_num = get_G_vector(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2026-01-04 20:53:41

t2 = q2+q3;
t3 = cos(t2);
t4 = t3.*1.4715;
G_num = [0.0;t4+cos(q2).*6.867;t4];
end
